name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Setup Pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.4
        run_install: true
    - id: get_increment
      name: Get Increment
      uses: ChocolateLoverRaj/detect-increment@v1.1
    - if: steps.get_increment.outputs.increment != 'none'
      name: Setup GitHub Author
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - if: steps.get_increment.outputs.increment != 'none'
      name: Semantic Release
      run: pnpx release-it ${{ steps.get_increment.outputs.increment }} --ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}